#!/bin/sh

# The only purpose of this file is to wrap the ec2dhcp script call into bash, because the
# dhcp-hook call ignore the shebang, and our scripts are all write for bash, not for dash.
bash /etc/network/ec2net.dhcp.sh