#!/bin/bash

# Copyright (C) 2013 Amazon.com, Inc. or its affiliates.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#    http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the
# License.

if [ $UID -ne 0 ]; then
  echo "error: ${0##*/} must be run as root"
  exit 1
fi

logger --tag ec2net "[ec2ifscan] Scanning for unconfigured interfaces"
for dev in $(find /sys/class/net/eth* /sys/class/net/ens*) ; do
  cfg="/etc/network/interfaces.d/if-${dev##*/}.cfg"
  state=$(cat ${dev}/operstate)
  if [ ! -e "${cfg}" ] && [ "${state}" == "down" ] ; then
    logger --tag ec2net "[ec2ifscan] Configuring ${dev##*/}"
    echo 'add' > ${dev}/uevent
  fi
done
